# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prana_forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
